config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
  	resources :comments
  end

  root 'posts#index'

  get '/about', to: 'pages#about'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end


	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at ASC')
  end

  def new
    @post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	
    if @post.save
  	   redirect_to @post

     else
      render 'new'
    end

  end

  def show
  	@post = Post.find(params[:id])
  	
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

      if @post.update(params[:post].permit(:title, :body))
          redirect_to @post
      else
        render 'edit'
      end 
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private 
  	def post_params
  		params.require(:post).permit(:title, :body)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
		<p>
			<%= link_to "Delete", [comment.post, comment],
						method: :delete,
						:class=> "button",
						:data=> {confirm: "Are you sure?"} %>
		</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f|%>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name%>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body%>
	</p><br>

	<p>
		<%= f.submit %>
	</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <div id="sidebar">
  	<div id="logo">
  		<%= link_to root_path do %>
  			<i class="small material-icons">fingerprint</i>
  		<%end%>
  	</div>
  	<ul>
  		<li class="category">Website</li>
  		<li> <%= link_to "Blog", root_path %></li>
  		<li><%= link_to "About", about_path %></li>
  	</ul>

  	<ul>
  		<li class="category">Social</li>
  		<li><a href="#">Twitter</a></li>
  		<li><a href="#">Facbook</a></li>
  		<li><a href="#">Instagram</a></li>
  	</ul>
  	<a class="sign_in">Adimin Login</a>
  </div>

 <div id="main_content">
 	<div id="header">
    <% if current_page?(root_path) %>
 		   <p>All Posts</p>
    <% elsif current_page?(about_path) %>
        <p>About</p>
    <% else %>
      <%= link_to "Back to All Posts", root_path %>
    <% end %>
    
 		<div class="buttons">
 			<button class="button"><%= link_to "new", new_post_path %></button>
 			<button class="button"><%= link_to "Logout"%></button>
 		</div>
 	</div>

 	<% flash.each do |name, msg|%>
 		<%= content_tag(:div, msg, :class=> "alert")%>
 	<%end%>

 	<%= yield %>
 </div>

  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="content">

		<h1>What is Lorem Ipsum?</h1>
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

		<h1>Why do we use it?</h1>
		<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>


		<h1>Where does it come from?</h1>
		<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%=form_for @post do |f| %>
	<%if @post.errors.any? %>
		<div id="errors">
			<h4><%= pluralize(@post.errors.count, "error") %> prevent this post from saving</h4>
			<ul>
				<% @post.errors.full_messages.each do |msg|%>
					<li><%= msg %></li>
				<%end%>
			</ul>
		</div>
	<%end%>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %><br>
		</p>
		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %><br>
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %>

app/views/posts/edit.html.erb
	
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form'%>
	
</div>

app/views/posts/index.html.erb
 <% @posts.each do |post| %>
 	<div class="post_wrapper">
	 	<h2 class="title"><%= link_to post.title, post %></h2>
	 	<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
	
<div id="page_wrapper">
	<h1>New posts</h1>

	<%=form_for :post, url: posts_path do |f| %>
		<%if @post.errors.any? %>
			<div id="errors">
				<h4><%= pluralize(@post.errors.count, "error") %> prevent this post from saving</h4>
				<ul>
					<% @post.errors.full_messages.each do |msg|%>
						<li><%= msg %></li>
					<%end%>
				</ul>
			</div>
		<%end%>

			<%= f.label :title %><br>
			<%= f.text_field :title %><br>
			<br>
			<%= f.label :body %><br>
			<%= f.text_area :body %><br>

			<%= f.submit %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	

	<h1 class="tittle"><%= @post.title %></h1>
	<p>Submitted <%= time_ago_in_words(@post.created_at) %> Ago</p>

	<p class="body"><%= @post.body %></p>

	<div class="buttons">
			<button class="button"><%= link_to "Edit", edit_post_path(@post)%></button> 
			<button class="button"><%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}%></button>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>

	</diV>
</div>	